---
repos:
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v0.6.1
    hooks:
      - id: nixpkgs-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.20.0
    hooks:
      - id: yamllint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-ci']
      - id: git-check
      - id: markdownlint
      # todo: send up MR to change /bin/bash /usr/bin/env bash
      # - id: script-must-have-extension
      # - id: script-must-not-have-extension
      - id: shellcheck
