local-bin-patt: ~/.stack/bin

# dont use system ghc, install if neeeded
system-ghc: false
install-ghc: true

templates:
  params:
    author-email: kyle@ondy.me
    author-name: Kyle Ondy
    copyright: '2016 Kyle Ondy <kyle@ondy.me>'
    github-username: kyleondy
